import 'package:flutter/material.dart';
import 'package:beebag/components/voucher_card.dart';

List<VoucherCard> voucherItems = [
    const VoucherCard(
      logoUrl: "assets/images/green_mart_logo.jpg",
      minSpend: "RM50",
      price: "3,800",
      validity: "31 Dec 2022",
      voucherName: "RM3 Voucher by Green Mart",
    ),
    const VoucherCard(
      logoUrl: "assets/images/happyshop.jpg",
      minSpend: "RM50",
      price: "3,800",
      validity: "3 feb 2022",
      voucherName: "RM3 Voucher by Happy Mart",
    ),
    const VoucherCard(
      logoUrl: "assets/images/cartify.jpeg",
      minSpend: "RM50",
      price: "3,800",
      validity: "31 Dec 2022",
      voucherName: "RM3 Voucher by Cartify",
    ),
    const VoucherCard(
      logoUrl: "assets/images/fresh.jpg",
      minSpend: "RM50",
      price: "3,800",
      validity: "31 Dec 2022",
      voucherName: "RM3 Voucher by Red Mart",
    ),
    const VoucherCard(
      logoUrl: "assets/images/green_mart_logo.jpg",
      minSpend: "RM50",
      price: "3,800",
      validity: "31 Dec 2022",
      voucherName: "RM3 Voucher by Red Mart",
    ),
    const VoucherCard(
      logoUrl: "assets/images/green_mart_logo.jpg",
      minSpend: "RM50",
      price: "3,800",
      validity: "31 Dec 2022",
      voucherName: "RM3 Voucher by Red Mart",
    ),
    const VoucherCard(
      logoUrl: "assets/images/green_mart_logo.jpg",
      minSpend: "RM50",
      price: "3,800",
      validity: "31 Dec 2022",
      voucherName: "RM3 Voucher by Green Mart",
    ),
    const VoucherCard(
      logoUrl: "assets/images/happyshop.jpg",
      minSpend: "RM50",
      price: "3,800",
      validity: "3 feb 2022",
      voucherName: "RM3 Voucher by Happy Mart",
    ),
    const VoucherCard(
      logoUrl: "assets/images/cartify.jpeg",
      minSpend: "RM50",
      price: "3,800",
      validity: "31 Dec 2022",
      voucherName: "RM3 Voucher by Cartify",
    ),
    const VoucherCard(
      logoUrl: "assets/images/fresh.jpg",
      minSpend: "RM50",
      price: "3,800",
      validity: "31 Dec 2022",
      voucherName: "RM3 Voucher by Red Mart",
    ),
    const VoucherCard(
      logoUrl: "assets/images/green_mart_logo.jpg",
      minSpend: "RM50",
      price: "3,800",
      validity: "31 Dec 2022",
      voucherName: "RM3 Voucher by Red Mart",
    ),
    const VoucherCard(
      logoUrl: "assets/images/green_mart_logo.jpg",
      minSpend: "RM50",
      price: "3,800",
      validity: "31 Dec 2022",
      voucherName: "RM3 Voucher by Red Mart",
    ),
    const VoucherCard(
      logoUrl: "assets/images/green_mart_logo.jpg",
      minSpend: "RM50",
      price: "3,800",
      validity: "31 Dec 2022",
      voucherName: "RM3 Voucher by Green Mart",
    ),
    const VoucherCard(
      logoUrl: "assets/images/happyshop.jpg",
      minSpend: "RM50",
      price: "3,800",
      validity: "3 feb 2022",
      voucherName: "RM3 Voucher by Happy Mart",
    ),
    const VoucherCard(
      logoUrl: "assets/images/cartify.jpeg",
      minSpend: "RM50",
      price: "3,800",
      validity: "31 Dec 2022",
      voucherName: "RM3 Voucher by Cartify",
    ),
    const VoucherCard(
      logoUrl: "assets/images/fresh.jpg",
      minSpend: "RM50",
      price: "3,800",
      validity: "31 Dec 2022",
      voucherName: "RM3 Voucher by Red Mart",
    ),
    const VoucherCard(
      logoUrl: "assets/images/green_mart_logo.jpg",
      minSpend: "RM50",
      price: "3,800",
      validity: "31 Dec 2022",
      voucherName: "RM3 Voucher by Green Mart",
    ),
    const VoucherCard(
      logoUrl: "assets/images/happyshop.jpg",
      minSpend: "RM50",
      price: "3,800",
      validity: "3 feb 2022",
      voucherName: "RM3 Voucher by Happy Mart",
    ),
    const VoucherCard(
      logoUrl: "assets/images/cartify.jpeg",
      minSpend: "RM50",
      price: "3,800",
      validity: "31 Dec 2022",
      voucherName: "RM3 Voucher by Cartify",
    ),
    const VoucherCard(
      logoUrl: "assets/images/fresh.jpg",
      minSpend: "RM50",
      price: "3,800",
      validity: "31 Dec 2022",
      voucherName: "RM3 Voucher by Red Mart",
    ),
    const VoucherCard(
      logoUrl: "assets/images/green_mart_logo.jpg",
      minSpend: "RM50",
      price: "3,800",
      validity: "31 Dec 2022",
      voucherName: "RM3 Voucher by Green Mart",
    ),
    const VoucherCard(
      logoUrl: "assets/images/happyshop.jpg",
      minSpend: "RM50",
      price: "3,800",
      validity: "3 feb 2022",
      voucherName: "RM3 Voucher by Happy Mart",
    ),
    const VoucherCard(
      logoUrl: "assets/images/cartify.jpeg",
      minSpend: "RM50",
      price: "3,800",
      validity: "31 Dec 2022",
      voucherName: "RM3 Voucher by Cartify",
    ),
    const VoucherCard(
      logoUrl: "assets/images/fresh.jpg",
      minSpend: "RM50",
      price: "3,800",
      validity: "31 Dec 2022",
      voucherName: "RM3 Voucher by Red Mart",
    ),
    const VoucherCard(
      logoUrl: "assets/images/green_mart_logo.jpg",
      minSpend: "RM50",
      price: "3,800",
      validity: "31 Dec 2022",
      voucherName: "RM3 Voucher by Red Mart",
    ),
    const VoucherCard(
      logoUrl: "assets/images/green_mart_logo.jpg",
      minSpend: "RM50",
      price: "3,800",
      validity: "31 Dec 2022",
      voucherName: "RM3 Voucher by Red Mart",
    ),
  ];